baseURL = "https://ritaliiii.github.io/"
languageCode = 'en-us'
title = 'Ning Li'
theme = "PaperMod"

[params]
  author = "Ning Li"
  showBreadCrumbs = true
  ShowReadingTime = true
  showCodeCopyButtons = true
  defaultTheme = "auto"
