baseURL = "https://ritaliiii.github.io/"
title = "Ning Li"
theme = "PaperMod"
publishDir = "docs"
[pagination]
  pagerSize = 5
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false


[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  title = "Ning Li"
  description = "Data Engineering | Data Analytics | Business Intelligence | Portfolio"
  keywords = ["Portfolio", "Data Engineering", "Data Analytics", "Business Intelligence"]
  # author = "Ning Li"
  defaultTheme = "auto"
  disableThemeToggle = false


  ShowAuthor = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = false
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true

[params.profileMode]
    enabled = true
    title = "Hey! I'm Ning 👋"
    subtitle = "Data Engineering | Data Analytics | Business Intelligence\n\nOpen to opportunities, let's connect!"
    imageUrl = "/images/ning.jpg"
    imageTitle = "Ning Li"
    imageWidth = 300
    imageHeight = 300

    [[params.profileMode.buttons]]
      name = "Projects"
      url = "/projects/"

    [[params.profileMode.buttons]]
      name = "Resume"
      url = "/resume.jpg"

[params.assets]
  css = ["css/custom.css"]

  # Social Icons
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/ritaliiii"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/ning-li-rita"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:li.ning2@northeastern.edu"

# Top navigation menu
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "experience"
    name = "Experience"
    url = "/experience/"
    weight = 20

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 30

  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume/"
    weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      

